name: skripsi_raymond
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0-nullsafety.2
  provider: ^6.0.1
  fluttertoast: ^8.0.2
  shared_preferences: any
  flutter_form_builder: ^6.0.0
  flutter_native_splash: ^1.3.1
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
